apiVersion: v1 
kind: ConfigMap
metadata:
  name: frontend
  namespace: expense
data:
  DB_HOST: backend 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web 
    project: expense
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: frontend
      tier: web 
      project: expense
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        tier: web 
        project: expense
    spec:
      containers:
      - name: frontend
        image: {{.Values.deployment.imageVersion}}
        envFrom:
        - configMapRef:
            name: frontend