apiVersion: v1 
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: {{.Values.serice.service_type}}
  selector:
      app: frontend
      tier: web 
      project: expense
  ports:
  - name: frontend-port
    protocol: TCP
    port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}