apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels: 
    app: mysql
    tier: db
    project: expense
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: manohar1481/mysql:{{ .Values.deployment.imageVersion }}
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-db-port
    protocol: TCP
    port: 3306
    targetPort: 3306


